services:
  web:
    image: devops-web
    depends_on:
    - mongodb
    build: 
      context: ./first-nodejs-app
    ports:
      - "3000:3000" # external port: internal port
    environment:
      MONGO_URL: mongodb://user:passw@mongodb:27017
      DB_NAME: myapp
  mongodb:
    image: mongo
    restart: always
    expose:
      - 27017
    volumes:
      - data_users:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=passw
      - MONGO_INITDB_DATABASE=myapp
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    expose:
      - 5672
    ports:
      - 15672:15672
    volumes:
      - data_rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports: 
      - 9090:9090
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
  grafana:
    build: ./grafana
    ports:
      - 3001:3000
volumes:
  data_users:
  data_rabbitmq:
  prometheus-data:

