services:
  # Authentication
  auth:
    image: cloud-auth
    depends_on:
    - mongodb_auth
    build: 
      context: ./authentication
    expose:
      - 3000
    environment:
      MONGO_URL: mongodb://user:passw@mongodb_auth:27017
      DB_NAME: auth
  mongodb_auth:
    image: mongo
    restart: always
    expose:
      - 27017
    volumes:
      - data_auth:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=passw
      - MONGO_INITDB_DATABASE=auth
  # Gateway
  gateway:
    image: cloud-gateway
    depends_on:
    - auth
    restart: always
    ports:
      - "8070:80" # external port: internal port
    environment:
    # List all the services that the gateway should be able to access
     - AUTH_ENDPOINT=http://auth:80

  # Service bus
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    expose:
      - 5672
    ports:
      - 15672:15672
    volumes:
      - data_rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  # Logging service
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports: 
      - 9090:9090
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
  grafana:
    build: ./grafana
    ports:
      - 3001:3000
volumes:
  data_users:
  data_auth:
  data_rabbitmq:
  prometheus-data:

