services:
  web:
    image: devops-web
    depends_on:
    - mongodb
    build: 
      context: ./first-nodejs-app
    ports:
      - "8080:3000" # external port: internal port
    environment:
      MONGO_URL: mongodb://user:passw@mongodb:27017
      DB_NAME: myapp
  mongodb:
    image: mongo
    restart: always
    expose:
      - 27017
    volumes:
      - data_users:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=passw
      - MONGO_INITDB_DATABASE=myapp
volumes:
  data_users:

