global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m

rule_files:
  - alert.yml

scrape_configs:
  - job_name: 'auth'
    static_configs:
      - targets:
          - '[auth]:3000'
        labels:
          instance: 'auth'
  - job_name: 'gateway'
    static_configs:
      - targets:
          - '[gateway]:3000'
        labels:
          instance: 'gateway'
  - job_name: 'like'
    static_configs:
      - targets:
          - '[like]:3000'
        labels:
          instance: 'like'
  - job_name: 'target'
    static_configs:
      - targets:
          - '[target]:3000'
        labels:
          instance: 'target'