global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m

rule_files:
  - alert.yml

scrape_configs:
  - job_name: 'web'
    static_configs:
      - targets:
          - '[web]:3000'
        labels:
          instance: 'web'